### ISSUE TITLE
报了很多错误

### ISSUE THREAD

**Issue by shawnwhale** [zhangxiaoya/FBSuperResolution#17]
CMakeFiles/FBSR.dir/build.make:62: recipe for target 'CMakeFiles/FBSR.dir/src/LKOFlow/LKOFlow.cpp.o' failed
make[2]: *** [CMakeFiles/FBSR.dir/src/LKOFlow/LKOFlow.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/FBSR.dir/all' failed
make[1]: *** [CMakeFiles/FBSR.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by zhangxiaoya** [comment]
> CMakeFiles/FBSR.dir/build.make:62: recipe for target 'CMakeFiles/FBSR.dir/src/LKOFlow/LKOFlow.cpp.o' failed
> make[2]: *** [CMakeFiles/FBSR.dir/src/LKOFlow/LKOFlow.cpp.o] Error 1
> CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/FBSR.dir/all' failed
> make[1]: *** [CMakeFiles/FBSR.dir/all] Error 2
> Makefile:83: recipe for target 'all' failed
> make: *** [all] Error 2

你描述一下情况，贴一些详细的日志。

**Comment by zhangxiaoya** [comment]
> CMakeFiles/FBSR.dir/build.make:62: recipe for target 'CMakeFiles/FBSR.dir/src/LKOFlow/LKOFlow.cpp.o' failed
> make[2]: *** [CMakeFiles/FBSR.dir/src/LKOFlow/LKOFlow.cpp.o] Error 1
> CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/FBSR.dir/all' failed
> make[1]: *** [CMakeFiles/FBSR.dir/all] Error 2
> Makefile:83: recipe for target 'all' failed
> make: *** [all] Error 2

需要安装OpenCV3的Extra的库

**Comment by zhangxiaoya** [comment]
@shawnwhale 需要opencv_contrib
